# Generated by Django 4.0.4 on 2022-04-29 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('producer', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('a', 'Action Adventure'), ('b', 'Comedy'), ('c', 'Drama'), ('d', 'Fantasy'), ('e', 'Horror'), ('f', 'Psychological'), ('g', 'Romance'), ('h', 'Sci-Fi'), ('i', 'Shoujo'), ('j', 'Shounen'), ('k', 'Slice of Life')], default='a', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('creator', models.CharField(max_length=250)),
                ('episodes', models.IntegerField()),
                ('language', models.CharField(choices=[('a', 'Japanese Original'), ('b', 'English Dub'), ('c', 'Portuguese Dub'), ('d', 'Spanish Dub'), ('e', 'Original Japanese/English Sub'), ('f', 'Original Japanese/Portuguese Sub'), ('g', 'Original Japanese/Spanish Sub')], default='a', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('a', 'Action Adventure'), ('b', 'Comedy'), ('c', 'Drama'), ('d', 'Fantasy'), ('e', 'Horror'), ('f', 'Psychological'), ('g', 'Romance'), ('h', 'Sci-Fi'), ('i', 'Shoujo'), ('j', 'Shounen'), ('k', 'Slice of Life')], default='a', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
