# Generated by Django 4.0.4 on 2022-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='anime',
            field=models.IntegerField(),
        ),
    ]
