# Generated by Django 4.0.3 on 2022-05-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_anime_creator_remove_anime_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
